# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SimpleAppObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleAppObjectiveC
  # Remote MonetaiSDK pod
  pod 'MonetaiSDK'
  
  # Add other dependencies if needed
  # pod 'Alamofire', '~> 5.8'

end 