# Monetai iOS SDK CocoaPods Integration Example

platform :ios, '16.0'
use_frameworks!

project 'CocoaPodsExample.xcodeproj'

target 'CocoaPodsExample' do
  # Monetai SDK via CocoaPods from remote repository
  pod 'MonetaiSDK', '1.0.0-beta.1'
  
  # RevenueCat integration
  pod 'RevenueCat'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end 